/* =====================================================================
   TeaTrade Trace · Certificates page
   ---------------------------------------------------------------------
  The Certificates page is the audit log. It lists every Tea ID
   ever generated by the importer (rows from public.trace_certificates),
   merged with a small set of curated demo certs so a brand-new account
   still has something to look at.

   Live rows are tagged with a "Live" chip and link straight back to
   the public Tea Passport page; clicking the QR pill re-opens the
   shareable QR modal via TTPassportQR.
   ===================================================================== */
(function () {
  'use strict';
  var D = window.TTData;
  var demoCerts = (D && D.certificates) ? D.certificates.slice() : [];

  /* state */
  var liveCerts = [];
  var allCerts  = demoCerts.slice();

  var grid    = document.getElementById('certGrid');
  var preview = document.getElementById('certPreview');
  var input   = document.getElementById('lookupInput');

  /* ---------- Mini-QR (decorative, demo certs only) ---------- */
  function miniQr(seed) {
    var s = 0; for (var k = 0; k < seed.length; k++) s = (s * 31 + seed.charCodeAt(k)) >>> 0;
    function rnd() { s = (s * 1103515245 + 12345) & 0x7fffffff; return s / 0x7fffffff; }
    var size = 9, html = '<svg viewBox="0 0 ' + size + ' ' + size + '" class="cert-qr">';
    for (var y = 0; y < size; y++) for (var x = 0; x < size; x++) {
      var f = (x < 3 && y < 3) || (x > size - 4 && y < 3) || (x < 3 && y > size - 4);
      if (f) {
        if (x === 0 || x === 2 || x === size - 1 || x === size - 3 || y === 0 || y === 2 || y === size - 1 || y === size - 3 || x === 1 && y === 1 || (x === size-2 && y === 1) || (x === 1 && y === size-2)) {
          html += '<rect x="'+x+'" y="'+y+'" width="1" height="1" fill="currentColor"/>';
        }
      } else if (rnd() > 0.55) {
        html += '<rect x="'+x+'" y="'+y+'" width="1" height="1" fill="currentColor"/>';
      }
    }
    html += '</svg>';
    return html;
  }

  function escapeHtml(s) {
    return String(s == null ? '' : s).replace(/[&<>"']/g, function (c) {
      return { '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c];
    });
  }

  /* ---------- Live cert fetch ---------- */
  /* Joins trace_certificates -> trace_lots so we can label each row with
     the estate name. Falls back gracefully if the table doesn't exist
     yet (migration not run) or there's no session. */
  async function fetchLiveCerts() {
    if (!window.TTSupabase || !TTSupabase.client || !TTSupabase.session) return [];
    try {
      var res = await TTSupabase.client
        .from('trace_certificates')
        .select('id, lot_id, kind, url, block_height, hash, scan_count, created_at, ' +
                'trace_lots(estate_name, status, stages_done)')
        .order('created_at', { ascending: false });
      if (res.error) {
        console.warn('[certificates] fetch:', res.error.message);
        return [];
      }
      return (res.data || []).map(function (r) {
        var lot = r.trace_lots || {};
        return {
          serial: r.lot_id,
          batch:  r.lot_id,
          estate: lot.estate_name || '—',
          hash:   r.hash || '—',
          scans:  r.scan_count || 0,
          minted: r.created_at,
          weight: null,
          co2:    null,
          isLive: true,
          url:    r.url,
          status: lot.status || null,
          kind:   r.kind || 'tea-passport'
        };
      });
    } catch (err) {
      console.warn('[certificates] fetch threw:', err && err.message);
      return [];
    }
  }

  /* ---------- KPIs ---------- */
  function paintKpis() {
    document.getElementById('kpiIssued').textContent = allCerts.length;
    var totalScans = allCerts.reduce(function (s, c) { return s + (c.scans || 0); }, 0);
    document.getElementById('kpiScans').textContent  = totalScans.toLocaleString();
  }

  /* ---------- Cert grid ---------- */
  function renderGrid() {
    if (!allCerts.length) {
      grid.innerHTML = '<div class="bento-card" style="grid-column:1/-1;text-align:center;color:var(--muted);padding:40px;">' +
        'No certificates issued yet. Generate one with the QR pill on any lot card.' +
      '</div>';
      return;
    }
    grid.innerHTML = allCerts.map(function (c) {
      var liveChip = c.isLive
        ? '<span class="chip chip--verified" title="Logged from your Tea Passport audit log">● Live</span>'
        : '<span class="chip">Demo</span>';
      var weightChip = (c.weight != null)
        ? '<span class="chip">' + c.weight + 't · ' + (c.co2 == null ? '—' : c.co2.toFixed(2)) + ' tCO₂e</span>'
        : (c.status ? '<span class="chip">' + escapeHtml(c.status) + '</span>' : '');
      return '<article class="cert-card" data-serial="' + escapeHtml(c.serial) + '">' +
        '<button class="card-pill card-pill--qr" type="button" data-qr-id="' + escapeHtml(c.batch || c.serial) + '" data-qr-label="' + escapeHtml(c.estate) + '" title="Open Tea Passport QR">QR</button>' +
        '<div style="display:flex;justify-content:space-between;align-items:flex-start;gap:12px;">' +
          '<div>' +
            '<p class="eyebrow" style="margin:0 0 6px;">' + (c.isLive ? 'Tea Passport · Logged' : 'Certificate · Verified') + '</p>' +
            '<h4 style="margin:0;font-size:16px;letter-spacing:.04em;word-break:break-all;">' + escapeHtml(c.serial) + '</h4>' +
          '</div>' +
          (c.isLive ? '' : '<span style="color:var(--accent);">' + miniQr(c.serial) + '</span>') +
        '</div>' +
        '<div style="font-size:13px;color:var(--muted);">' + escapeHtml(c.estate) + '</div>' +
        '<div class="cert-meta-row"><span>Lot</span><strong>' + escapeHtml(c.batch) + '</strong></div>' +
        '<div class="cert-meta-row"><span>Hash</span><strong style="font-family:var(--font-mono);font-size:12px;">' + escapeHtml((c.hash || '').slice(0,18)) + '…</strong></div>' +
        '<div class="cert-meta-row"><span>Scans</span><strong>' + (c.scans || 0).toLocaleString() + '</strong></div>' +
        '<div class="cert-meta-row"><span>Issued</span><strong>' + escapeHtml(TTChrome.fmtDate(c.minted)) + '</strong></div>' +
        '<div style="display:flex;gap:6px;margin-top:auto;flex-wrap:wrap;">' +
          liveChip +
          weightChip +
        '</div>' +
      '</article>';
    }).join('');
  }

  grid.addEventListener('click', function (e) {
    /* let the QR pill handle its own clicks */
    if (e.target.closest('.card-pill')) return;
    var card = e.target.closest('.cert-card'); if (!card) return;
    var serial = card.getAttribute('data-serial');
    var c = allCerts.find(function (x) { return x.serial === serial; });
    if (c) {
      input.value = serial;
      renderPreview(c, true);
      document.querySelector('.cert-lookup').scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  });

  /* ---------- Lookup preview ---------- */
  function renderPreview(c, instant) {
    if (!instant) {
      preview.innerHTML = '<p class="muted-text" style="margin:0;text-align:center;">Resolving…</p>';
    }
    var html;
    if (c.isLive) {
      var idUrl = c.url || ('https://trace.teatrade.co.uk/id/' + c.serial);
      html =
        '<div style="display:flex;justify-content:space-between;align-items:flex-start;gap:14px;margin-bottom:14px;">' +
          '<div>' +
            '<p class="eyebrow" style="margin:0 0 4px;">Tea ID · Live</p>' +
            '<h3 style="margin:0;font-size:18px;letter-spacing:.04em;word-break:break-all;">' + escapeHtml(c.serial) + '</h3>' +
          '</div>' +
        '</div>' +
        '<div class="cert-meta-row"><span>Estate</span><strong>' + escapeHtml(c.estate) + '</strong></div>' +
        '<div class="cert-meta-row"><span>Status</span><strong>' + escapeHtml(c.status || '—') + '</strong></div>' +
        '<div class="cert-meta-row"><span>Manifest hash</span><strong style="font-family:var(--font-mono);font-size:12px;">' + escapeHtml((c.hash || '—').slice(0,24)) + '…</strong></div>' +
        '<div class="cert-meta-row"><span>Scans</span><strong>' + (c.scans || 0).toLocaleString() + '</strong></div>' +
        '<div class="cert-meta-row"><span>Issued</span><strong>' + escapeHtml(TTChrome.fmtDate(c.minted)) + '</strong></div>' +
        '<div style="margin-top:14px;padding:10px 12px;border-radius:8px;background:rgba(30,142,62,0.08);color:var(--verified);font-weight:500;font-size:13px;display:flex;align-items:center;gap:8px;">' +
          '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg>' +
          'Signed and logged in your audit trail' +
        '</div>' +
        '<div style="display:flex;gap:8px;margin-top:12px;">' +
          '<button class="btn btn--ghost" type="button" data-qr-id="' + escapeHtml(c.batch || c.serial) + '" data-qr-label="' + escapeHtml(c.estate) + '" style="flex:1;">Re-open QR</button>' +
          '<a class="btn btn--primary" href="' + escapeHtml(passportUrl) + '" target="_blank" rel="noopener" style="flex:1;text-align:center;text-decoration:none;">Open Tea Passport →</a>' +
        '</div>';
    } else {
      var b = D.batches.find(function (x) { return x.id === c.batch; });
      var e = b ? D.estateById(b.estate) : { name: c.estate, country: '—' };
      html =
        '<div style="display:flex;justify-content:space-between;align-items:flex-start;gap:14px;margin-bottom:14px;">' +
          '<div>' +
            '<p class="eyebrow" style="margin:0 0 4px;">Verified · ISAE 3000</p>' +
            '<h3 style="margin:0;font-size:18px;letter-spacing:.04em;">' + escapeHtml(c.serial) + '</h3>' +
          '</div>' +
          '<span style="color:var(--accent);font-size:48px;line-height:1;">' + miniQr(c.serial).replace('cert-qr', 'cert-qr cert-qr--lg') + '</span>' +
        '</div>' +
        '<div class="cert-meta-row"><span>Estate</span><strong>' + escapeHtml(e.name) + '</strong></div>' +
        '<div class="cert-meta-row"><span>Country</span><strong>' + escapeHtml(e.country) + '</strong></div>' +
        '<div class="cert-meta-row"><span>Batch</span><strong>' + escapeHtml(c.batch) + '</strong></div>' +
        '<div class="cert-meta-row"><span>Weight</span><strong>' + c.weight + ' t</strong></div>' +
        '<div class="cert-meta-row"><span>Carbon</span><strong>' + (c.co2 == null ? '—' : c.co2.toFixed(2) + ' tCO₂e') + '</strong></div>' +
        '<div class="cert-meta-row"><span>Manifest hash</span><strong style="font-family:var(--font-mono);font-size:12px;">' + escapeHtml(c.hash) + '</strong></div>' +
        '<div class="cert-meta-row"><span>Scans</span><strong>' + (c.scans || 0).toLocaleString() + '</strong></div>' +
        '<div style="margin-top:14px;padding:10px 12px;border-radius:8px;background:rgba(30,142,62,0.08);color:var(--verified);font-weight:500;font-size:13px;display:flex;align-items:center;gap:8px;">' +
          '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg>' +
          'Signature valid · 4 of 4 attestations verified' +
        '</div>' +
        '<div style="display:flex;gap:8px;margin-top:12px;">' +
          '<button class="btn btn--ghost" style="flex:1;">View on chain</button>' +
          '<button class="btn btn--primary" style="flex:1;">Download PDF</button>' +
        '</div>';
    }

    if (instant) preview.innerHTML = html;
    else setTimeout(function () { preview.innerHTML = html; }, 350);
  }

  function lookup(query) {
    if (!query) {
      preview.innerHTML = '<p class="muted-text" style="margin:0;text-align:center;">Awaiting lookup…</p>';
      return;
    }
    var q = query.trim().toLowerCase();
    var c = allCerts.find(function (x) {
      return (x.serial || '').toLowerCase() === q || (x.hash || '').toLowerCase() === q || (x.batch || '').toLowerCase() === q;
    });
    if (!c) {
      c = allCerts.find(function (x) {
        return (x.serial || '').toLowerCase().indexOf(q) !== -1 || (x.hash || '').toLowerCase().indexOf(q) !== -1;
      });
    }
    if (c) renderPreview(c);
    else {
      preview.innerHTML = '<p style="margin:0;text-align:center;color:#d93025;">No certificate found for <code>' + escapeHtml(query) + '</code></p>';
    }
  }

  input.addEventListener('input', function () { lookup(input.value); });
  document.getElementById('sampleHash').addEventListener('click', function () {
    var first = allCerts[0];
    if (!first) return;
    input.value = first.hash;
    lookup(first.hash);
  });

  /* ---------- Boot ---------- */
  /* Initial render with demo data so the page is never blank,
     then merge in live rows once Supabase responds. */
  paintKpis();
  renderGrid();

  (async function () {
    if (window.TTSupabase && TTSupabase.ready) {
      try { await TTSupabase.ready; } catch (_) {}
    }
    liveCerts = await fetchLiveCerts();
    if (liveCerts.length) {
      var seen = {};
      liveCerts.forEach(function (c) { seen[c.serial] = true; });
      var demoFiltered = demoCerts.filter(function (c) { return !seen[c.serial]; });
      allCerts = liveCerts.concat(demoFiltered);
      paintKpis();
      renderGrid();
    }
  })();

  /* Auto-lookup if hash present */
  if (location.hash) {
    var serial = decodeURIComponent(location.hash.substring(1));
    input.value = serial;
    lookup(serial);
  }
})();
